# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "k8s-master"
  config.vm.box = "centos/7"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 8001, host: 8081
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.synced_folder "C:\\Data", "/data", type: "virtualbox"
  config.vbguest.auto_update = true
  config.vbguest.no_remote = false
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
end



 