# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "k8s-node1"
  config.vm.box = "centos/7"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.synced_folder "C:\\Data", "/data", type: "virtualbox"
  config.vbguest.auto_update = true
  config.vbguest.no_remote = false
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 1
    end
end



 