apiVersion: v1
kind: Service
metadata:
  name: my-example
spec:
  selector:
    app: example
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  selector:
    matchLabels:
      app: example
  replicas: 3
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: example
          image: gcr.io/google-samples/hello-app:2.0
          ports:
            - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
    - host: mywebserver
      http:
        paths:
          - path: /
            backend:
              serviceName: my-example
              servicePort: 8080
